version: "3.9"
services:
  web:
    image: hiveer/topic-api:0.0.3
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
    command: npm start
    ports:
      - "3600:3600"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
