version: "3.9"
services:
  web:
    build: .
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
    ports:
      - "3600:3600"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
